### ISSUE TITLE
count_data.ipynb Incorrectly Says "Harmonic" Mean

### ISSUE THREAD

**Issue by GeoffNordling** [AllenDowney/DataQnA#1]
There is a typo at this part:

"""
def bootstrap_mean(data):
    resampled = np.random.choice(data, size=len(data), replace=True)
    return np.mean(resampled)
If we call this function 1000 times, we get a sample from from sampling distribution of the harmonic mean.
"""

This is normal mean! I think you said "harmonic" because you had recently done a different post with harmonic mean.

**Comment by AllenDowney** [comment]
Fixed. Thank you!
